language: scala
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.coursier"
script:
  sbt test
notifications:
  email:
  - caoilte@gmail.com
branches:
  only:
  - master
